server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
    headers:
      - "Content-Type"
      - "Authorization"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "HEAD"
      - "OPTIONS"
    origins:
      - "*"
  grpc:
    addr: 0.0.0.0:9090
    timeout: 1s

#registry:
#  type: "consul"
#  consul:
#    address: 127.0.0.1:8500
#    scheme: http
#    health_check: false

#data:
#  redis:
#    addr: 127.0.0.1:6379
#    read_timeout: 0.2s
#    write_timeout: 0.2s

#auth:
#  service_key: some-secret-key
#  api_key: some-secret-key-for-frontend

trace:
  endpoint: 127.0.0.1:6831